#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumBoard.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ScrumOtomasyon")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_PROJELER(TBL_PROJELER instance);
    partial void UpdateTBL_PROJELER(TBL_PROJELER instance);
    partial void DeleteTBL_PROJELER(TBL_PROJELER instance);
    partial void InsertTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void UpdateTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void DeleteTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void InsertTBL_SCRUM1(TBL_SCRUM1 instance);
    partial void UpdateTBL_SCRUM1(TBL_SCRUM1 instance);
    partial void DeleteTBL_SCRUM1(TBL_SCRUM1 instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::ScrumBoard.Properties.Settings.Default.ScrumOtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_PROJELER> TBL_PROJELERs
		{
			get
			{
				return this.GetTable<TBL_PROJELER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KULLANICILAR> TBL_KULLANICILARs
		{
			get
			{
				return this.GetTable<TBL_KULLANICILAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SCRUM1> TBL_SCRUM1s
		{
			get
			{
				return this.GetTable<TBL_SCRUM1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PROJELERS")]
	public partial class TBL_PROJELER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PROJEKODU;
		
		private string _PROJEADI;
		
		private string _PROJEONEMI;
		
		private string _PROJEADISOYADI;
		
		private string _PROJETELEFON;
		
		private string _PROJEMAIL;
		
		private System.Nullable<System.DateTime> _PROJEBASLANGICTARIHI;
		
		private System.Nullable<System.DateTime> _PROJEBITISTARIHI;
		
		private System.Data.Linq.Binary _PROJERESIM;
		
		private System.Nullable<int> _PROJESAVEUSER;
		
		private System.Nullable<System.DateTime> _PROJESAVEDATE;
		
		private System.Nullable<int> _PROJEEDITUSER;
		
		private System.Nullable<System.DateTime> _PROJEEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPROJEKODUChanging(string value);
    partial void OnPROJEKODUChanged();
    partial void OnPROJEADIChanging(string value);
    partial void OnPROJEADIChanged();
    partial void OnPROJEONEMIChanging(string value);
    partial void OnPROJEONEMIChanged();
    partial void OnPROJEADISOYADIChanging(string value);
    partial void OnPROJEADISOYADIChanged();
    partial void OnPROJETELEFONChanging(string value);
    partial void OnPROJETELEFONChanged();
    partial void OnPROJEMAILChanging(string value);
    partial void OnPROJEMAILChanged();
    partial void OnPROJEBASLANGICTARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnPROJEBASLANGICTARIHIChanged();
    partial void OnPROJEBITISTARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnPROJEBITISTARIHIChanged();
    partial void OnPROJERESIMChanging(System.Data.Linq.Binary value);
    partial void OnPROJERESIMChanged();
    partial void OnPROJESAVEUSERChanging(System.Nullable<int> value);
    partial void OnPROJESAVEUSERChanged();
    partial void OnPROJESAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPROJESAVEDATEChanged();
    partial void OnPROJEEDITUSERChanging(System.Nullable<int> value);
    partial void OnPROJEEDITUSERChanged();
    partial void OnPROJEEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPROJEEDITDATEChanged();
    #endregion
		
		public TBL_PROJELER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEKODU", DbType="NVarChar(20)")]
		public string PROJEKODU
		{
			get
			{
				return this._PROJEKODU;
			}
			set
			{
				if ((this._PROJEKODU != value))
				{
					this.OnPROJEKODUChanging(value);
					this.SendPropertyChanging();
					this._PROJEKODU = value;
					this.SendPropertyChanged("PROJEKODU");
					this.OnPROJEKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEADI", DbType="NVarChar(50)")]
		public string PROJEADI
		{
			get
			{
				return this._PROJEADI;
			}
			set
			{
				if ((this._PROJEADI != value))
				{
					this.OnPROJEADIChanging(value);
					this.SendPropertyChanging();
					this._PROJEADI = value;
					this.SendPropertyChanged("PROJEADI");
					this.OnPROJEADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEONEMI", DbType="NVarChar(5)")]
		public string PROJEONEMI
		{
			get
			{
				return this._PROJEONEMI;
			}
			set
			{
				if ((this._PROJEONEMI != value))
				{
					this.OnPROJEONEMIChanging(value);
					this.SendPropertyChanging();
					this._PROJEONEMI = value;
					this.SendPropertyChanged("PROJEONEMI");
					this.OnPROJEONEMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEADISOYADI", DbType="NVarChar(75)")]
		public string PROJEADISOYADI
		{
			get
			{
				return this._PROJEADISOYADI;
			}
			set
			{
				if ((this._PROJEADISOYADI != value))
				{
					this.OnPROJEADISOYADIChanging(value);
					this.SendPropertyChanging();
					this._PROJEADISOYADI = value;
					this.SendPropertyChanged("PROJEADISOYADI");
					this.OnPROJEADISOYADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJETELEFON", DbType="NVarChar(15)")]
		public string PROJETELEFON
		{
			get
			{
				return this._PROJETELEFON;
			}
			set
			{
				if ((this._PROJETELEFON != value))
				{
					this.OnPROJETELEFONChanging(value);
					this.SendPropertyChanging();
					this._PROJETELEFON = value;
					this.SendPropertyChanged("PROJETELEFON");
					this.OnPROJETELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEMAIL", DbType="NVarChar(90)")]
		public string PROJEMAIL
		{
			get
			{
				return this._PROJEMAIL;
			}
			set
			{
				if ((this._PROJEMAIL != value))
				{
					this.OnPROJEMAILChanging(value);
					this.SendPropertyChanging();
					this._PROJEMAIL = value;
					this.SendPropertyChanged("PROJEMAIL");
					this.OnPROJEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEBASLANGICTARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> PROJEBASLANGICTARIHI
		{
			get
			{
				return this._PROJEBASLANGICTARIHI;
			}
			set
			{
				if ((this._PROJEBASLANGICTARIHI != value))
				{
					this.OnPROJEBASLANGICTARIHIChanging(value);
					this.SendPropertyChanging();
					this._PROJEBASLANGICTARIHI = value;
					this.SendPropertyChanged("PROJEBASLANGICTARIHI");
					this.OnPROJEBASLANGICTARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEBITISTARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> PROJEBITISTARIHI
		{
			get
			{
				return this._PROJEBITISTARIHI;
			}
			set
			{
				if ((this._PROJEBITISTARIHI != value))
				{
					this.OnPROJEBITISTARIHIChanging(value);
					this.SendPropertyChanging();
					this._PROJEBITISTARIHI = value;
					this.SendPropertyChanged("PROJEBITISTARIHI");
					this.OnPROJEBITISTARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJERESIM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PROJERESIM
		{
			get
			{
				return this._PROJERESIM;
			}
			set
			{
				if ((this._PROJERESIM != value))
				{
					this.OnPROJERESIMChanging(value);
					this.SendPropertyChanging();
					this._PROJERESIM = value;
					this.SendPropertyChanged("PROJERESIM");
					this.OnPROJERESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJESAVEUSER", DbType="Int")]
		public System.Nullable<int> PROJESAVEUSER
		{
			get
			{
				return this._PROJESAVEUSER;
			}
			set
			{
				if ((this._PROJESAVEUSER != value))
				{
					this.OnPROJESAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._PROJESAVEUSER = value;
					this.SendPropertyChanged("PROJESAVEUSER");
					this.OnPROJESAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJESAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PROJESAVEDATE
		{
			get
			{
				return this._PROJESAVEDATE;
			}
			set
			{
				if ((this._PROJESAVEDATE != value))
				{
					this.OnPROJESAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._PROJESAVEDATE = value;
					this.SendPropertyChanged("PROJESAVEDATE");
					this.OnPROJESAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEEDITUSER", DbType="Int")]
		public System.Nullable<int> PROJEEDITUSER
		{
			get
			{
				return this._PROJEEDITUSER;
			}
			set
			{
				if ((this._PROJEEDITUSER != value))
				{
					this.OnPROJEEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._PROJEEDITUSER = value;
					this.SendPropertyChanged("PROJEEDITUSER");
					this.OnPROJEEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PROJEEDITDATE
		{
			get
			{
				return this._PROJEEDITDATE;
			}
			set
			{
				if ((this._PROJEEDITDATE != value))
				{
					this.OnPROJEEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._PROJEEDITDATE = value;
					this.SendPropertyChanged("PROJEEDITDATE");
					this.OnPROJEEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KULLANICILAR")]
	public partial class TBL_KULLANICILAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KULLANICIADI;
		
		private string _KULLANICISIFRE;
		
		private string _KULLANICIADSOYAD;
		
		private System.Nullable<bool> _KULLANICIAKTIF;
		
		private string _KULLANICIKODU;
		
		private System.Nullable<System.DateTime> _KULLANICISAVEDATE;
		
		private System.Nullable<System.DateTime> _KULLANICIEDITDATE;
		
		private System.Nullable<System.DateTime> _KULLANICILASTLOGIN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKULLANICIADIChanging(string value);
    partial void OnKULLANICIADIChanged();
    partial void OnKULLANICISIFREChanging(string value);
    partial void OnKULLANICISIFREChanged();
    partial void OnKULLANICIADSOYADChanging(string value);
    partial void OnKULLANICIADSOYADChanged();
    partial void OnKULLANICIAKTIFChanging(System.Nullable<bool> value);
    partial void OnKULLANICIAKTIFChanged();
    partial void OnKULLANICIKODUChanging(string value);
    partial void OnKULLANICIKODUChanged();
    partial void OnKULLANICISAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKULLANICISAVEDATEChanged();
    partial void OnKULLANICIEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnKULLANICIEDITDATEChanged();
    partial void OnKULLANICILASTLOGINChanging(System.Nullable<System.DateTime> value);
    partial void OnKULLANICILASTLOGINChanged();
    #endregion
		
		public TBL_KULLANICILAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICIADI", DbType="NVarChar(50)")]
		public string KULLANICIADI
		{
			get
			{
				return this._KULLANICIADI;
			}
			set
			{
				if ((this._KULLANICIADI != value))
				{
					this.OnKULLANICIADIChanging(value);
					this.SendPropertyChanging();
					this._KULLANICIADI = value;
					this.SendPropertyChanged("KULLANICIADI");
					this.OnKULLANICIADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICISIFRE", DbType="NVarChar(50)")]
		public string KULLANICISIFRE
		{
			get
			{
				return this._KULLANICISIFRE;
			}
			set
			{
				if ((this._KULLANICISIFRE != value))
				{
					this.OnKULLANICISIFREChanging(value);
					this.SendPropertyChanging();
					this._KULLANICISIFRE = value;
					this.SendPropertyChanged("KULLANICISIFRE");
					this.OnKULLANICISIFREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICIADSOYAD", DbType="NVarChar(150)")]
		public string KULLANICIADSOYAD
		{
			get
			{
				return this._KULLANICIADSOYAD;
			}
			set
			{
				if ((this._KULLANICIADSOYAD != value))
				{
					this.OnKULLANICIADSOYADChanging(value);
					this.SendPropertyChanging();
					this._KULLANICIADSOYAD = value;
					this.SendPropertyChanged("KULLANICIADSOYAD");
					this.OnKULLANICIADSOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICIAKTIF", DbType="Bit")]
		public System.Nullable<bool> KULLANICIAKTIF
		{
			get
			{
				return this._KULLANICIAKTIF;
			}
			set
			{
				if ((this._KULLANICIAKTIF != value))
				{
					this.OnKULLANICIAKTIFChanging(value);
					this.SendPropertyChanging();
					this._KULLANICIAKTIF = value;
					this.SendPropertyChanged("KULLANICIAKTIF");
					this.OnKULLANICIAKTIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICIKODU", DbType="NVarChar(50)")]
		public string KULLANICIKODU
		{
			get
			{
				return this._KULLANICIKODU;
			}
			set
			{
				if ((this._KULLANICIKODU != value))
				{
					this.OnKULLANICIKODUChanging(value);
					this.SendPropertyChanging();
					this._KULLANICIKODU = value;
					this.SendPropertyChanged("KULLANICIKODU");
					this.OnKULLANICIKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICISAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KULLANICISAVEDATE
		{
			get
			{
				return this._KULLANICISAVEDATE;
			}
			set
			{
				if ((this._KULLANICISAVEDATE != value))
				{
					this.OnKULLANICISAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._KULLANICISAVEDATE = value;
					this.SendPropertyChanged("KULLANICISAVEDATE");
					this.OnKULLANICISAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICIEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KULLANICIEDITDATE
		{
			get
			{
				return this._KULLANICIEDITDATE;
			}
			set
			{
				if ((this._KULLANICIEDITDATE != value))
				{
					this.OnKULLANICIEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._KULLANICIEDITDATE = value;
					this.SendPropertyChanged("KULLANICIEDITDATE");
					this.OnKULLANICIEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICILASTLOGIN", DbType="DateTime")]
		public System.Nullable<System.DateTime> KULLANICILASTLOGIN
		{
			get
			{
				return this._KULLANICILASTLOGIN;
			}
			set
			{
				if ((this._KULLANICILASTLOGIN != value))
				{
					this.OnKULLANICILASTLOGINChanging(value);
					this.SendPropertyChanging();
					this._KULLANICILASTLOGIN = value;
					this.SendPropertyChanged("KULLANICILASTLOGIN");
					this.OnKULLANICILASTLOGINChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SCRUM1")]
	public partial class TBL_SCRUM1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _PROJEID;
		
		private System.Nullable<int> _KULLANICILARID;
		
		private string _SCRUMBASLIK;
		
		private string _SCRUMEKLENECEKYER;
		
		private string _SCRUMONEMI;
		
		private System.Nullable<System.DateTime> _SCRUMZAMAN;
		
		private string _SCRUMGOREVLI;
		
		private string _SCRUMACIKLAMA;
		
		private System.Nullable<int> _SCRUMSAVEUSER;
		
		private System.Nullable<System.DateTime> _SCRUMSAVEDATE;
		
		private System.Nullable<int> _SCRUMEDITUSER;
		
		private System.Nullable<System.DateTime> _SCRUMEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPROJEIDChanging(System.Nullable<int> value);
    partial void OnPROJEIDChanged();
    partial void OnKULLANICILARIDChanging(System.Nullable<int> value);
    partial void OnKULLANICILARIDChanged();
    partial void OnSCRUMBASLIKChanging(string value);
    partial void OnSCRUMBASLIKChanged();
    partial void OnSCRUMEKLENECEKYERChanging(string value);
    partial void OnSCRUMEKLENECEKYERChanged();
    partial void OnSCRUMONEMIChanging(string value);
    partial void OnSCRUMONEMIChanged();
    partial void OnSCRUMZAMANChanging(System.Nullable<System.DateTime> value);
    partial void OnSCRUMZAMANChanged();
    partial void OnSCRUMGOREVLIChanging(string value);
    partial void OnSCRUMGOREVLIChanged();
    partial void OnSCRUMACIKLAMAChanging(string value);
    partial void OnSCRUMACIKLAMAChanged();
    partial void OnSCRUMSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSCRUMSAVEUSERChanged();
    partial void OnSCRUMSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCRUMSAVEDATEChanged();
    partial void OnSCRUMEDITUSERChanging(System.Nullable<int> value);
    partial void OnSCRUMEDITUSERChanged();
    partial void OnSCRUMEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCRUMEDITDATEChanged();
    #endregion
		
		public TBL_SCRUM1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROJEID", DbType="Int")]
		public System.Nullable<int> PROJEID
		{
			get
			{
				return this._PROJEID;
			}
			set
			{
				if ((this._PROJEID != value))
				{
					this.OnPROJEIDChanging(value);
					this.SendPropertyChanging();
					this._PROJEID = value;
					this.SendPropertyChanged("PROJEID");
					this.OnPROJEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KULLANICILARID", DbType="Int")]
		public System.Nullable<int> KULLANICILARID
		{
			get
			{
				return this._KULLANICILARID;
			}
			set
			{
				if ((this._KULLANICILARID != value))
				{
					this.OnKULLANICILARIDChanging(value);
					this.SendPropertyChanging();
					this._KULLANICILARID = value;
					this.SendPropertyChanged("KULLANICILARID");
					this.OnKULLANICILARIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMBASLIK", DbType="NVarChar(75)")]
		public string SCRUMBASLIK
		{
			get
			{
				return this._SCRUMBASLIK;
			}
			set
			{
				if ((this._SCRUMBASLIK != value))
				{
					this.OnSCRUMBASLIKChanging(value);
					this.SendPropertyChanging();
					this._SCRUMBASLIK = value;
					this.SendPropertyChanged("SCRUMBASLIK");
					this.OnSCRUMBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMEKLENECEKYER", DbType="NVarChar(50)")]
		public string SCRUMEKLENECEKYER
		{
			get
			{
				return this._SCRUMEKLENECEKYER;
			}
			set
			{
				if ((this._SCRUMEKLENECEKYER != value))
				{
					this.OnSCRUMEKLENECEKYERChanging(value);
					this.SendPropertyChanging();
					this._SCRUMEKLENECEKYER = value;
					this.SendPropertyChanged("SCRUMEKLENECEKYER");
					this.OnSCRUMEKLENECEKYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMONEMI", DbType="NVarChar(5)")]
		public string SCRUMONEMI
		{
			get
			{
				return this._SCRUMONEMI;
			}
			set
			{
				if ((this._SCRUMONEMI != value))
				{
					this.OnSCRUMONEMIChanging(value);
					this.SendPropertyChanging();
					this._SCRUMONEMI = value;
					this.SendPropertyChanged("SCRUMONEMI");
					this.OnSCRUMONEMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMZAMAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCRUMZAMAN
		{
			get
			{
				return this._SCRUMZAMAN;
			}
			set
			{
				if ((this._SCRUMZAMAN != value))
				{
					this.OnSCRUMZAMANChanging(value);
					this.SendPropertyChanging();
					this._SCRUMZAMAN = value;
					this.SendPropertyChanged("SCRUMZAMAN");
					this.OnSCRUMZAMANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMGOREVLI", DbType="NVarChar(50)")]
		public string SCRUMGOREVLI
		{
			get
			{
				return this._SCRUMGOREVLI;
			}
			set
			{
				if ((this._SCRUMGOREVLI != value))
				{
					this.OnSCRUMGOREVLIChanging(value);
					this.SendPropertyChanging();
					this._SCRUMGOREVLI = value;
					this.SendPropertyChanged("SCRUMGOREVLI");
					this.OnSCRUMGOREVLIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string SCRUMACIKLAMA
		{
			get
			{
				return this._SCRUMACIKLAMA;
			}
			set
			{
				if ((this._SCRUMACIKLAMA != value))
				{
					this.OnSCRUMACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._SCRUMACIKLAMA = value;
					this.SendPropertyChanged("SCRUMACIKLAMA");
					this.OnSCRUMACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMSAVEUSER", DbType="Int")]
		public System.Nullable<int> SCRUMSAVEUSER
		{
			get
			{
				return this._SCRUMSAVEUSER;
			}
			set
			{
				if ((this._SCRUMSAVEUSER != value))
				{
					this.OnSCRUMSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SCRUMSAVEUSER = value;
					this.SendPropertyChanged("SCRUMSAVEUSER");
					this.OnSCRUMSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCRUMSAVEDATE
		{
			get
			{
				return this._SCRUMSAVEDATE;
			}
			set
			{
				if ((this._SCRUMSAVEDATE != value))
				{
					this.OnSCRUMSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SCRUMSAVEDATE = value;
					this.SendPropertyChanged("SCRUMSAVEDATE");
					this.OnSCRUMSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMEDITUSER", DbType="Int")]
		public System.Nullable<int> SCRUMEDITUSER
		{
			get
			{
				return this._SCRUMEDITUSER;
			}
			set
			{
				if ((this._SCRUMEDITUSER != value))
				{
					this.OnSCRUMEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._SCRUMEDITUSER = value;
					this.SendPropertyChanged("SCRUMEDITUSER");
					this.OnSCRUMEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRUMEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCRUMEDITDATE
		{
			get
			{
				return this._SCRUMEDITDATE;
			}
			set
			{
				if ((this._SCRUMEDITDATE != value))
				{
					this.OnSCRUMEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._SCRUMEDITDATE = value;
					this.SendPropertyChanged("SCRUMEDITDATE");
					this.OnSCRUMEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
